### ISSUE TITLE
[Django] Hide Django Secret Key

### ISSUE THREAD

**Issue by rvthai** [rvthai/budget-buddy#1]
# Background
On project initialization, Django automatically creates a `settings.py` file, which potentially has some configurations or keys that must be kept secret.

# Motivation
To prevent some information, such as the _Django Secret Key_, from being exposed through the repo, I need to use environment variables. 

# Tasks
- [ ] Create a new Django Secret Key (since old one has been exposed in commit history)
- [ ] Install Python `dotenv `package and create a `.env` file
- [ ] `.gitignore` the `.env` file
- [ ] Update the` settings.py` file

# Resources
- [Stackoverflow: I committed my secret key to a private repository.](https://stackoverflow.com/questions/56874713/django-2-3-i-committed-my-secret-key-to-a-private-repository-can-i-just-edit-t)

**Comment by Moali97** [comment]
Could I have a go at this?
